name: somethingtrue
favicon: null
layout_spectrum: 0.5995192560367286
typography_spectrum: 0.46010252134874463
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7366860369220376
  lightness: 0.45033721067011356
  saturation: 0.7001983388327062
  rhythmicContrast: 0.645376113243401
purpose: []
